index:
    path: /
    methods: GET
    controller: App\Controller\PostController::index

add_post:
    path: /post/publish
    methods: POST
    controller: App\Controller\PostController::publishPost

show_post:
    path: /post/{postId}
    methods: GET
    controller: App\Controller\PostController::viewPost

delete_post:
    path: /post/{postId}/delete
    methods: POST
    controller: App\Controller\PostController::deletePost

list_posts:
    path: /post/list/all
    methods: GET
    controller: App\Controller\PostController::listPosts
