index:
    path: /
    methods: GET
    controller: App\Controller\PostController::index

add_post:
    path: /post/publish
    methods: POST
    controller: App\Controller\PostController::publishPost

show_post:
    path: /post/{postId}
    methods: GET
    controller: App\Controller\PostController::viewPost
